mali_kbase: mem: __GFP_ATOMIC
Upstream kernel commit [1] has dropped __GFP_ATOMIC,
so this here fails compilation:
.../common/../private/google-modules/gpu/mali_kbase/mali_kbase_mem_linux.c:672:23: error: use of undeclared identifier '__GFP_ATOMIC'
        WARN((sc->gfp_mask & __GFP_ATOMIC),
                             ^
1 error generated.

Update the code by following the example of tegra-smmu.c in same
upstream kernel commit.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2973d8229b78
    ("mm: discard __GFP_ATOMIC")

Bug: 277062866
Test: build and boot, TH
Change-Id: I50f9c06c19f4ea62478431fd7ab856007c015283
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>